In [1]:
import pickle

In [2]:
# Carregando o Modelo Treinado
rede_neural = pickle.load(open('D:/Puc Minas/Projeto/TCC/rede_neural_finalizado.sav', 'rb'))

In [3]:
# Carregando a Base de dados
registros = pickle.load(open('D:/Puc Minas/Projeto/TCC/bases_classificacao.pkl', 'rb'))

In [4]:
# Selecionando primeiro registro das variáveis independentes (X)
# 0-dataset, 1-dataset_original, 2-X, 3-Y, 4-empresa
registros[2][0]

array([ 0.03120541,  0.38514598, -0.36966732, -0.03607148, -0.05189065,
        0.39860908,  0.03491883,  1.494266  ,  0.30833631, -0.49741454,
        0.03535085, -0.08078732,  0.02143708, -0.02119222,  0.00370107,
        0.0178347 , -0.0079188 ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [5]:
novo_registro = registros[2][0]

In [6]:
type(novo_registro)

numpy.ndarray

In [7]:
novo_registro.shape

(39,)

In [8]:
# Convertendo em uma Matriz de 1 linha e 39 colunas
novo_registro = novo_registro.reshape(1, -1)

In [9]:
type(novo_registro)

numpy.ndarray

In [10]:
novo_registro.shape

(1, 39)

In [11]:
# Aplicando o modelo no registro selecionado e prevendo a classificação
rede_neural.predict(novo_registro)

array([1], dtype=int64)

In [12]:
# Verificando o Segundo Registro
segundo_registro = registros[2][1]
segundo_registro = segundo_registro.reshape(1, -1)

In [13]:
rede_neural.predict(segundo_registro)

array([0], dtype=int64)

In [14]:
registros[1]

DS_CONTA CD_CVM                              DENOM_CIA ticker  \
0            94                      PANATLANTICA S.A.  PATI3   
1          2429           IRANI PAPEL E EMBALAGEM S.A.  RANI3   
2          3069     CIA FERRO LIGAS DA BAHIA - FERBASA  FESA3   
3          3980                            GERDAU S.A.  GGBR3   
4          4030               CIA SIDERURGICA NACIONAL  CSNA3   
...         ...                                    ...    ...   
2590      25453                         INTELBRAS S.A.  INTB3   
2591      25461                             MOBLY S.A.  MBLY3   
2592      25470  MOSAICO TECNOLOGIA AO CONSUMIDOR S.A.  MOSI3   
2593      25500                BEMOBI MOBILE TECH S.A.  BMOB3   
2594      25747               INFRACOMMERCE CXAAS S.A.  IFCM3   

DS_CONTA           SETOR ECONÔMICO                     SEGMENTO DT_FIM_EXERC  \
0                Materiais Básicos     Artefatos de Ferro e Aço   2010-12-31   
1                Materiais Básicos             Papel e Celulose   2010-12-31   
2                Materiais Básicos                   Siderurgia   2010-12-31   
3                Materiais Básicos                   Siderurgia   2010-12-31   
4                Materiais Básicos                   Siderurgia   2010-12-31   
...                            ...                          ...          ...   
2590      Tecnologia da Informação  Computadores e Equipamentos   2020-12-31   
2591      Tecnologia da Informação         Programas e Serviços   2020-12-31   
2592      Tecnologia da Informação         Programas e Serviços   2020-12-31   
2593      Tecnologia da Informação         Programas e Serviços   2020-12-31   
2594      Tecnologia da Informação         Programas e Serviços   2020-12-31   

DS_CONTA  Liquidez Corrente  Liquidez Geral  Endividamento Geral  \
0                  2.393471        1.649168             0.489053   
1                  0.900699        0.679481             0.591941   
2                  6.298481        5.326603             0.133013   
3                  2.577898        0.707945             0.530263   
4                  3.544400        0.715798             0.793057   
...                     ...             ...                  ...   
2590               1.889455        1.428416             0.600258   
2591               0.825271        0.672905             1.060300   
2592               1.630752        1.579889             0.508682   
2593               0.735240        0.780513             0.661592   
2594               0.967081        0.713231             0.859749   

DS_CONTA  Partic Cap Terc  ...       ROA  Margem Bruta  Margem Líquida  \
0                0.957152  ...  0.071804      0.116574        0.052869   
1                1.450624  ...  0.030016      0.391551        0.077619   
2                0.153419  ...  0.112689      0.287928        0.199047   
3                1.128850  ...  0.057293      0.175826        0.078277   
4                3.832254  ...  0.066564      0.468064        0.174125   
...                   ...  ...       ...           ...             ...   
2590             1.501613  ...  0.134290      0.328355        0.153654   
2591           -17.583725  ... -0.129782      0.400541       -0.066748   
2592             1.035340  ...  0.270016      0.921289        0.261119   
2593             1.955015  ...  0.078196      0.592477        0.208282   
2594             6.130065  ... -0.015524      0.497590       -0.027694   

DS_CONTA       RPL        QDC      PEVA      PGVA      PTVA      PAVA  Classe  
0        -0.007165  -0.280569  0.144109  0.378304  0.244559  0.233028       1  
1         0.076979  -0.932132  0.258124  0.195195  0.398707  0.133176       0  
2         0.079004   2.507419  0.353230  0.322343  0.019914  0.304513       1  
3         0.205440   0.458201  0.398460  0.241507  0.178479  0.000000       1  
4         0.317351  -0.996821  0.169124  0.279476  0.230260  0.321140       1  
...            ...        ...       ...       ...       ...       ...   

#### Testando outros registros

In [15]:
rede_neural.predict(registros[2][2592].reshape(1, -1))

array([1], dtype=int64)

In [16]:
rede_neural.predict(registros[2][2594].reshape(1, -1))

array([0], dtype=int64)

In [17]:
rede_neural.predict(registros[2][3].reshape(1, -1))

array([1], dtype=int64)